11 entrep referent 11 ajouter une entreprise
jcheron/offres pull request #36
Opened 2023-04-15 10:04 UTC by fbarre61

En tant que réfèrent, je peux :
Ajouter une entreprise à la liste :
Inscrire le code postal afin d'avoir la (les) ville(s) correspondante(s) pour une saisie plus rapide
Voir les entreprises déjà existantes en bas selon leur RS
Je peux être informé si une entreprise que j'ai voulu ajouté existe déjà et peut modifier la RS en conséquent en gardant les informations précédemment saisies

2023-04-15 11:18 UTC, jcheron reviewed
Pourquoi y a-t-il 2 PR différentes pour le même code ?

2023-04-15 11:25 UTC, fbarre61 commented
Celle vers supavenir c'est une erreur d'inattention de ma part, elle ne va pas servir

2023-04-15 21:28 UTC, Nathannicolle approved these changes
Great work !

2023-04-16 10:01 UTC, merged

2023-04-16 10:12 UTC, jcheron requested changes
dossier `target` à enlever du repo et des commits

2023-04-16 10:12 UTC, jcheron commented on src/main/resources/templates/entrep/form.html
> +        fetch("/entrep/rs?contenu=" + encodeURIComponent(contenu)).then(async function (response) {
On a une liste d'entreprises, mais l'utilisateur en fait quoi ?