20 cand referent 20 lister les candidats par formation
jcheron/offres pull request #37
Opened 2023-04-15 21:03 UTC by Nathannicolle

Listage de l'ensemble des candidats triés par ordre de création ou par formation.

2023-04-15 21:25 UTC, fbarre61 approved these changes

2023-04-16 09:52 UTC, jcheron requested changes
Pas mal,
Enlever le dossier `target` du repository et des commits

2023-04-16 09:52 UTC, jcheron commented on src/main/resources/static/js/candidat.js
> +                  /*let tbodyContentByFormation = requestBody.match(/<tbody>([\s\S]*?)<\/tbody>/i)[0].replace(/(<tbody>|<\/tbody>)/gmi, "");
A enlever...

2023-04-16 09:52 UTC, jcheron commented on src/main/resources/static/js/candidat.js
> +                  /*let tbody = requestBody.match(/<tbody>([\s\S]*?)<\/tbody>/i)[0].replace(/(<tbody>|<\/tbody>)/gmi, "");
idem

2023-04-16 09:52 UTC, jcheron commented on src/main/resources/static/js/candidat.js
> +         document.querySelectorAll(".checkbox_candidat").forEach((oneCheckbox) => {
Répétition de code, à factoriser

2023-04-16 09:52 UTC, jcheron commented on src/main/resources/templates/candidat/index.html
> +                        <td>{{email}}</td>
Il faudrait quand même afficher dans une colonne la liste des formations sur lesquelles postule le candidat

2023-04-16 13:57 UTC, jcheron approved these changes
Ca marche !

2023-04-16 15:08 UTC, merged